set_property(GLOBAL PROPERTY SOURCE_COLLECTION "")
set_property(GLOBAL PROPERTY INCLUDE_DIRECTORIES_COLLECTION "")

function(append_sources SRCS)
    if(SRCS)
        set(SRCS_NORMALIZED "")
        foreach(SRC ${SRCS})
            get_filename_component(SRC_ABS "${SRC}" ABSOLUTE)
            list(APPEND SRCS_NORMALIZED "${SRC_ABS}")
        endforeach()

        get_property(SRCS_GLOBAL GLOBAL PROPERTY SOURCE_COLLECTION)
        list(APPEND SRCS_GLOBAL ${SRCS_NORMALIZED})
        list(REMOVE_DUPLICATES SRCS_GLOBAL)
        set_property(GLOBAL PROPERTY SOURCE_COLLECTION "${SRCS_GLOBAL}")
    endif()
endfunction()

function(collect_sources target)
    get_target_property(SRCS ${target} SOURCES)
    if(NOT SRCS)
        get_target_property(SRCS ${target} INTERFACE_SOURCES)
        if(NOT SRCS)
            return()
        endif()
    endif()

    append_sources("${SRCS}")
endfunction()

function(append_include_directories INC_DIRS)
    if (INC_DIRS)
        set(INC_DIRS_NORMALIZED "")
        foreach(INC_DIR ${INC_DIRS})
            get_filename_component(INC_DIR_ABS "${INC_DIR}" ABSOLUTE)
            list(APPEND INC_DIRS_NORMALIZED "${INC_DIR_ABS}")
        endforeach()

        get_property(INC_DIRS_GLOBAL GLOBAL PROPERTY INCLUDE_DIRECTORIES_COLLECTION)
        list(APPEND INC_DIRS_GLOBAL ${INC_DIRS_NORMALIZED})
        list(REMOVE_DUPLICATES INC_DIRS_GLOBAL)
        set_property(GLOBAL PROPERTY INCLUDE_DIRECTORIES_COLLECTION "${INC_DIRS_GLOBAL}")
    endif()
endfunction()

function(collect_include_directories target)
    get_target_property(INC_DIRS ${target} INCLUDE_DIRECTORIES)
    if(NOT INC_DIRS)
        get_target_property(INC_DIRS ${target} INTERFACE_INCLUDE_DIRECTORIES)
        if(NOT INC_DIRS)
            return()
        endif()
    endif()

    append_include_directories("${INC_DIRS}")
endfunction()